### ISSUE TITLE
Restrict index calculation by (legal) mode access

### ISSUE THREAD

**Issue by christian-werner** [plus-mobilitylab/netascore#7]
By default, an index value was always created for segments that are accessible by at least one of the modes (car, bike, walk). This lead to misinterpretation of visual outputs when no filter was applied in post-processing. Therefore, the settings file should allow for restricting index computation to segments that are (legally) accessible per mode. However, users should still be able to compute a theoretical index for segments with restricted access, making it more versatile for specific applications in planning.

**Comment by christian-werner** [comment]
Solution: When referencing a mode profile in the settings file, the following parameters can be specified:
- filter_access_car: True
- filter_access_bike: True
- filter_access_walk: True
A full example could look like this:
```
profiles:
  -
    profile_name: bike
    filename: profile_bike.yml
    filter_access_bike: True
```

Combining filters is also supported:
```
profiles:
  -
    profile_name: bike_incwalk
    filename: profile_bike.yml
    filter_access_bike: True
    filter_access_walk: True
```
In this case, a "bike" index is computed for all segments that are accessible by bike as well as segments accessible for pedestrians (with restricted bike access).

If no filter parameters are specified, an index is computed for all segments accessible to at least one of the main modes (car, bike, walk) - thereby providing consistency with the legacy versions of NetAScore.
